version: "3.x"
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

# version: "3.x"
# services:
#   mongodb_container:
#     image: mongo:latest
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: password
#     ports:
#       - 27017:27017
#     volumes:
#       - mongodb_data_container:/data/db
#     command: >
#       /bin/bash -c "
#       apt-get update &&
#       apt-get install -y mongodb-clients &&
#       mongod --bind_ip_all"
# volumes:
#   mongodb_data_container:
